# Generated by Django 3.2.5 on 2022-02-11 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtube', '0002_auto_20220209_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(default='', max_length=200)),
                ('desc', models.TextField(default='', max_length=5000)),
                ('videoFile', models.FileField(default='', max_length=200, upload_to='public/videos/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtube.channels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
