# Generated by Django 3.2.5 on 2022-02-13 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vtube', '0005_alter_videos_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videos',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(default='', max_length=200, upload_to='public/videos/thumbnail'),
        ),
    ]
