# Generated by Django 3.2.5 on 2023-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtube', '0007_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='vid_id',
            field=models.IntegerField(default=0),
        ),
    ]
